#!/usr/bin/env bash

set -o errexit

REPO_URL=https://github.com/protiumx/autoenv.git
REPO_PATH="$HOME/.autoenv"

reset_color=$(tput sgr 0)

info() {
  printf "%s[*] %s%s\n" "$(tput setaf 2)" "$1" "$reset_color"
}

warn() {
  printf "%s[*] %s%s\n" "$(tput setaf 3)" "$1" "$reset_color"
}


install_xcode() {
  if xcode-select -p > /dev/null; then
    warn "XCode Command Line Tools already installed"
  else
    info "Installing XCode Command Line Tools..."
    xcode-select --install
    sudo xcodebuild -license accept
  fi
}

install_homebrew() {
  if hash brew &>/dev/null; then
    warn "Homebrew already installed"
  else
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
    sudo --validate  # reset `sudo` timeout to use Homebrew install in noninteractive mode
    CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

install_brew_formula() {
  if brew list --formula | grep "$1" > /dev/null; then
    warn "Formula $1 is already installed"
  else
    info "Installing package < $1 >"
    brew install "$1"
  fi
}

bootstrap() {
  info "Bootstraping..."
  info "Installing xcode"
  install_xcode

  info "Installing HomeBrew"
  install_homebrew

  info "Installing python3"
  install_brew_formula "python3"
  
  info "Installing git"
  install_brew_formula "git"

  PATH="/usr/local/bin:$(/opt/homebrew/bin/python3 -m site --user-base)/bin:$PATH"
  export PATH

  info "Installing pip"
  curl https://bootstrap.pypa.io/get-pip.py | python3
}

info "======= autoenv =======\n"

read -p "Sign in on the App Store first. Press enter to continue:"
bootstrap

info "Cloning autoenv repo from $REPO_URL into $REPO_PATH"
git clone "$REPO_URL" "$REPO_PATH"

info "Change path to $REPO_PATH"
cd "$REPO_PATH" >/dev/null

info "Creating Virtual Env"
python3 -m pip install --user virtualenv
virtualenv venv
. venv/bin/activate

info "Installing Ansible"
pip install ansible

info "Setting up Ansible"
ansible-galaxy collection install -r setup/requirements.yml

ANSIBLE_CONFIG=setup/setup.cfg ansible-playbook setup/main.yml \
  --extra-vars current_hostname="$(hostname -s)" --extra-vars github_token="$GITHUB_TOKEN"

info "Running autoenv Playbook"

ansible-playbook -vvv --ask-become-pass playbooks/autoenv.yml

info "Running post-install\n"
sh ./post-install.sh

info "Finished"
