---

- name: Check vim-plug file
  stat:
    path: ~/.local/share/nvim/site/autoload/plug.vim
    register: vim_plug

- name: Install neovim plugin manager
  ansible.builtin.shell: sh -c 'curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  when: not vim_plug.stat.exists


