---

- name: Install Homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew['taps'] }}"
  tags: [packages, homebrew_taps]

- name: Install Homebrew formulas
  community.general.homebrew:
    name: "{{ homebrew['formulas'] }}"
  tags: [packages, homebrew_formulas]

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew['casks'] }}"
    accept_external_apps: true
  tags: [packages, homebrew_casks]

- name: Install app store apps
  ansible.builtin.command: "mas install {{ item }}"
  loop: "{{ homebrew['mas'] }}"
  tags: [packages, mac_app_store]
