---

- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: 0755

- name: Create SSH key
  community.crypto.openssh_keypair:
    path: "{{ ansible_user_dir }}/.ssh/id_{{ item['key'] }}"
    passphrase: "{{ ssh_passphrase }}"
    type: "{{ item['key'] }}"
    size: 4096
    comment: "{{ ansible_user_id }}@{{ ansible_hostname }} {{ ansible_date_time['date'] }}"
  loop: "{{ ssh_keys | dict2items }}"
  loop_control:
    label: "{{ item['key'] }}"

- name: Copy SSH keys
  ansible.builtin.copy:
    src: "{{ item['src'] }}"
    dest: "{{ ansible_user_dir }}/.ssh"
    mode: "{{ '0644' if 'pub' in item['src'] | basename else '0600' }}"
  loop: "{{ lookup('community.general.filetree', 'ssh/') }}"
  loop_control:
    label: "{{ item['src'] | basename }}"
  when: manage_ssh_config and (item['src'] | basename != 'config')
