---

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: macos
  become: true

- name: Put display to sleep after 15 minutes and computer to sleep after 30 minutes
  ansible.builtin.shell: pmset displaysleep 15 && pmset sleep 30
  changed_when: false
  become: true
  tags: power_settings

- name: Unhide ~/Library
  ansible.builtin.shell: "chflags nohidden {{ ansible_user_dir }}/Library"
  changed_when: false
  tags: unhide_dirs

- name: Remove extended attributes on ~/Library
  ansible.builtin.shell: "xattr -c {{ ansible_user_dir }}/Library"
  changed_when: false
  tags: unhide_dirs
