---

backups_dir: "{{ ansible_user_dir }}/.ansible/backups"

bash_shell: /usr/local/bin/bash

python_user_path: "{{ ansible_user_dir }}/Library/Python/3.{{ ansible_python['version']['minor'] }}/bin"

pip: "/usr/local/bin/pip3.{{ ansible_python['version']['minor'] }}"

root_home: /var/root
