---

- name: Autoenv Ansible Setup
  hosts: localhost

  vars:
    default_hostname: "{{ current_hostname if current_hostname is defined else '' }}"

  vars_prompt:
    - name: hostname
      prompt: Enter system hostname
      private: false
      default: "{{ default_hostname }}"

    - name: email
      prompt: Enter email address
      private: false

    - name: ssh_key_types_to_generate
      prompt: SSH key types to generate (ed25519,rsa|None)
      private: false
      default: "ed25519"

    - name: manage_ssh_config
      prompt: Manage SSH config (True|False)
      private: false
      default: true
    
    - name: ssh_phrase
      prompt: Insert SSH phrase
      private: false
      
    - name: upload_ssh_key_github
      prompt: Upload SSH key to Github (True|False)
      private: false
      default: true

  tasks:
    - name: Create inventory
      ansible.builtin.template:
        src: inventory.yml.j2
        dest: "{{ ansible_user_dir }}/.ansible/inventory.yml"
        mode: 0755
