---

- name: Autoenv Tasks
  hosts: localhost
  tasks:
    - name: Import packages
      ansible.builtin.include_tasks: "tasks/packages.yml"
      tags: always

    - name: Import system settings
      ansible.builtin.include_tasks: "tasks/system.yml"
      tags: always

    - name: Create ~/Development folder structure
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/Development/{{ item }}"
        state: directory
        mode: 0755
      loop: ['protiumx']
      tags: [dev, core]

    - name: Install Dotfiles
      ansible.builtin.command: sh ~/.autoenv/dotfiles/install.sh
      tags: dotfiles

    - name: Set VSCode as default editor
      ansible.builtin.shell: |
        local exts=("{{ fileExtensions | join(' ') }}")
        for ext in $exts; do
        duti -s com.microsoft.VSCode $ext all
        done

        exit 0
      tags: settings

    - name: Import nvim tasks
      ansible.builtin.import_tasks: tasks/nvim.yml
      tags: [nvim, settings]

    - name: Import ssh tasks
      ansible.builtin.import_tasks: tasks/ssh.yml
      when: manage_ssh_config
      tags: [ssh, core]

    - name: Import GitHub tasks
      ansible.builtin.import_tasks: tasks/github.yml
      tags: github

    - name: Install Python packages
      ansible.builtin.pip:
        executable: "{{ pip[ansible_distribution] }}"
        name: "{{ pypi_packages }}"
        extra_args: --user
      tags: [core, python]

    - name: Disable startup sound
      shell: sudo nvram SystemAudioVolume=%01
      tags: settings
