---

- name: Install and configure dotfiles on localhost
  hosts: localhost

  tasks:
    - name: Create ~/Development folder structure
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/Development/{{ item }}"
        state: directory
        mode: 0755
      loop: ['protiumx']
      tags: core

    - name: Create dotfiles directory structure
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/{{ item }}"
        state: directory
        mode: 0755
      loop: ['.config/nvim', '.config/kitty', '.git-templates/hooks', '.ssh']
      tags: core

    - name: Stow dotfiles
      ansible.builtin.shell: |
        stow -d ~/.autoenv/dotfiles --verbose 1 --target ~/ git
        stow -d ~/.autoenv/dotfiles --verbose 1 --target ~/ kitty
        stow -d ~/.autoenv/dotfiles --verbose 1 --target ~/ nvim
        stow -d ~/.autoenv/dotfiles --verbose 1 --target ~/ ssh
        stow -d ~/.autoenv/dotfiles --verbose 1 --target ~/ vim
        stow -d ~/.autoenv/dotfiles --verbose 1 --target ~/ zsh

        exit 0

    - name: Import nvim tasks
      ansible.builtin.import_tasks: tasks/nvim.yml
      tags: [nvim, core]

    - name: Import ssh tasks
      ansible.builtin.import_tasks: tasks/ssh.yml
      tags: [ssh, core]

    - name: Import GitHub tasks
      ansible.builtin.import_tasks: tasks/github.yml
      tags: github

    - name: Install Python packages
      ansible.builtin.pip:
        executable: "{{ pip[ansible_distribution] }}"
        name: "{{ pypi_packages }}"
        extra_args: --user
      tags: python

    - name: Disable startup sound
      shell: sudo nvram SystemAudioVolume=%01
      tags: core
